context:
  name: pointblank
  version: "0.8.1"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pointblank/pointblank-${{ version }}.tar.gz
  sha256: ebfd5040f4219d4be5144222ae6427c70c615c7d264752f4a16457b46702deb0

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools_scm >=6.2
  run:
    - python >=${{ python_min }}
    - commonmark >=0.9.1
    - importlib-metadata
    - great_tables >=0.17.0
    - narwhals >=1.24.1
    - requests >=2.31.0
    - typing_extensions >=3.10.0.0

tests:
  - python:
      imports:
        - pointblank
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Find out if your data is what you think it is.
  homepage: https://posit-dev.github.io/pointblank/
  repository: https://github.com/posit-dev/pointblank

extra:
  recipe-maintainers:
    - rich-iannone
    - timkpaine
